### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/site#13]
Today our contact form is made by WordPress, we need to change, maybe, to LimeSurvey.

## Challenge
- [ ] Our site is static and a contact form need to send the content to an API and process the response.
- [ ] Check if we will put our email available on site because if we do this, would be possible receive a lot of SPAM
- [ ] Check the possibility to integrate the answers with our CRM

## Suggestion of to-do
- [ ] Implement the form at LimeSurvey side and apply a theme like of librecode.coop
- [ ] Configure the plugin to send the messages to a Telegram group. Use as reference the contact form of LibreCode page
- [ ] Implement the iframe on site: https://github.com/LibreCodeCoop/site/blob/master/source/_layouts/master.blade.php#L52 URL of iframe: https://ls.librecode.coop/index.php?r=survey/index&sid=746228&lang=pt-BR
    Motivation: dedicate less time to finish this task
- [ ] Create follow up issue to replace the iframe by another solution

**Comment by Any97Cris** [comment]
Form Before


![Image](https://github.com/LibreSign/libresign-www/assets/54338576/8d1cd406-77a3-48cc-b0b4-1bf53bcdd5f1)

Form After


![Image](https://github.com/LibreSign/libresign-www/assets/54338576/128679ea-11fc-493b-931d-27592a671afc)

**Comment by vitormattos** [comment]
Closed by #19
