### ISSUE TITLE
[Seção "Did you know..."] - Alteração textual

### ISSUE THREAD

**Issue by DaianeAlvesRJ** [LibreSign/site#168]
Na seção: "Você sabia que a assinatura digital é a forma mais segura e eficiente de validar documentos eletrônicos?"
Trocar o texto para:

Inglês: By using digital certificates issued by a Certification Authority, it is possible to ensure the signer's identity and the document's integrity. Physical signatures can be forged, compromising the validity of your documents. However, digital signatures, regulated by Provisional Measure No. 2.200-2/2001, provide the necessary security to protect the authenticity and legal validity of your documents.

Português: Ao utilizar certificados digitais emitidos por uma Autoridade Certificadora, é possível garantir a identidade do signatário e a integridade do documento. Assinaturas físicas podem ser falsificadas, comprometendo a validade dos seus documentos. No entanto, as assinaturas digitais, regulamentadas pela Medida Provisória nº 2.200-2/2001, oferecem a segurança necessária para proteger a autenticidade e a validade jurídica dos seus documentos.

**Comment by Any97Cris** [comment]
Adjustment was finished
