### ISSUE TITLE
Artigos para o site

### ISSUE THREAD

**Issue by DaianeAlvesRJ** [LibreSign/site#18]
Criação dos seguintes artigos para serem colocados no nosso site novo.
@luamellol você pode ajudar? Os artigos devem ser em inglês, mas se preferir deixar aqui mesmo a versão traduzida, não tem problema. Daí quando o texto estiver revisado a gente traduz. ;-)

- [x] Free and Open-Source
- [x] Multiple signers
- [x] Hybrid signatures
- [x] Qrcode validation

**Comment by DaianeAlvesRJ** [comment]
Os artigos encontram-se em: https://cloud.librecode.coop/apps/files/files/727875?dir=/LibreCode/Produtos/LibreSign/Artigos%20para%20o%20site&openfile=true

**Comment by vitormattos** [comment]
Movi a issue para cá pois estava no repo do LibreSign
