### ISSUE TITLE
Add alt text to pagination of testimonials

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/site#234]
The alt text need to be a translatable text. A screen reader will read back_comments. Maybe would be best:
Go back pagination of testimonials.

_Originally posted by @vitormattos in https://github.com/LibreSign/site/pull/223#discussion_r1731807261_

**Comment by Any97Cris** [comment]
I've added a supposed solution to the above comment, check in this link: https://github.com/LibreSign/site/pull/240/files
